# Generated by Django 2.2 on 2019-04-22 19:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('registration_number', models.CharField(default='2016-814-413', max_length=70)),
                ('hall_name', models.CharField(default='Dr. muhammad sahidullah hall', max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('admission_year', models.PositiveIntegerField(default=1980)),
                ('phone_number', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
